version: "3.8"

services:
  db:
    image: postgres:16
    env_file:
      - .env.postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    env_file:
      - .env.postgres

volumes:
  pgdata:
