version: "3.8"

services:
  app:
    build: .
    image: petclinic-app:latest
    container_name: petclinic-app
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
