version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: petclinic
      MYSQL_USER: pet
      MYSQL_PASSWORD: petpw
      MYSQL_ROOT_PASSWORD: rootpw
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - petclinic-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080"
    environment:
      SPRING_PROFILES_ACTIVE: mysql
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/petclinic
      SPRING_DATASOURCE_USERNAME: pet
      SPRING_DATASOURCE_PASSWORD: petpw
    depends_on:
      - db
    networks:
      - petclinic-net
    
volumes:
  db-data:

networks:
  petclinic-net:
